name: Build Installer

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build FFmpeg Installer
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: |
          pip install -r requirements.txt
          python update.py
      - name: Compile
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        if: ${{ hashFiles('default.iss') != '' }}        
        with:
          path: default.iss
          options: /O+
      - name: Upload to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.TOKEN }}
          files: dist/ffmpeg-setup.exe